# Generated by Django 6.0.8 on 2026-09-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile money'), ('card', 'Carte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
    ]
