# Generated by Django 6.0.8 on 2026-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_non_negative_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('XOF', 'XOF'), ('XAF', 'XAF'), ('GNF', 'GNF'), ('CDF', 'CDF'), ('MAD', 'MAD'), ('DZD', 'DZD'), ('NGN', 'NGN'), ('GHS', 'GHS'), ('KES', 'KES'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('CHF', 'CHF')], default='XOF', max_length=3),
        ),
    ]
