# Generated by Django 6.0.8 on 2026-10-08 14:43

from django.db import migrations, models


def stock_quantity_from_quantity(apps, schema_editor):
    # Lignes existantes : vendues dans l'unité unique du médicament, donc 1 pour 1.
    InvoiceLine = apps.get_model("billing", "InvoiceLine")
    InvoiceLine.objects.filter(medication__isnull=False).update(stock_quantity=models.F("quantity"))


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='sale_unit',
            field=models.CharField(choices=[('pack', 'Conditionnement'), ('unit', 'Unité')], default='unit', max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(stock_quantity_from_quantity, migrations.RunPython.noop),
    ]
