# Generated by Django 6.0.8 on 2026-08-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergies', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='clinics.clinic')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['clinic'], name='medical_rec_clinic__12ebbc_idx')],
            },
        ),
    ]
