# Generated by Django 6.0.8 on 2026-08-21 16:12

import clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_billing_cycle_clinic_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=clinics.models.clinic_logo_upload_path),
        ),
        migrations.AddField(
            model_name='clinic',
            name='locale',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2),
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to=clinics.models.clinic_logo_upload_path),
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo_light',
            field=models.ImageField(blank=True, null=True, upload_to=clinics.models.clinic_logo_upload_path),
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo_print',
            field=models.ImageField(blank=True, null=True, upload_to=clinics.models.clinic_logo_upload_path),
        ),
    ]
