# Generated by Django 6.0.8 on 2026-09-02 00:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_favicon_clinic_locale_clinic_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_clinic_name_ci'),
        ),
    ]
