# Generated by Django 6.0.8 on 2026-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_logos_in_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='inpatient_billing_mode',
            field=models.CharField(choices=[('flat', 'Flat rate'), ('per_room_type', 'Per room type')], default='flat', max_length=16),
        ),
        migrations.AddField(
            model_name='clinic',
            name='inpatient_nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
