# Generated by Django 6.0.8 on 2026-10-07 13:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_currency'),
        ('clinics', '0006_logos_in_database'),
        ('consultations', '0002_translatable_choices'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Demandé'), ('collected', 'Prélevé'), ('in_progress', 'En traitement'), ('completed', 'Terminé'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='requested', max_length=20)),
                ('clinical_note', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='clinics.clinic')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='consultations.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='doctors.doctor')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=30)),
                ('test_name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.laborderitem')),
            ],
            options={
                'ordering': ['-entered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LabResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('content', models.BinaryField()),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='laboratory.labresult')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit', models.CharField(blank=True, help_text='Ex. g/L, mmol/L.', max_length=30)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['clinic', 'status'], name='laboratory__clinic__e15916_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient'], name='laboratory__patient_11fe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['doctor'], name='laboratory__doctor__a2f281_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.UniqueConstraint(fields=('clinic', 'number'), name='unique_lab_order_number_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['item', 'superseded_at'], name='laboratory__item_id_abdc92_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['clinic', 'is_active'], name='laboratory__clinic__110293_idx'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.UniqueConstraint(fields=('clinic', 'code'), name='unique_lab_test_code_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='lab_test_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.CheckConstraint(condition=models.Q(('reference_min__isnull', True), ('reference_max__isnull', True), ('reference_max__gte', models.F('reference_min')), _connector='OR'), name='lab_test_reference_max_gte_min'),
        ),
    ]
