# Generated by Django 6.0.8 on 2026-08-10 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('cancel', 'Cancel'), ('archive', 'Archive'), ('view', 'View'), ('print', 'Print'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission change')], max_length=32)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='clinics.clinic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='common_audi_clinic__a8347a_idx'), models.Index(fields=['model_name', 'object_id'], name='common_audi_model_n_d26c0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_counters', to='clinics.clinic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('clinic', 'key', 'year'), name='unique_sequence_per_clinic_key_year')],
            },
        ),
    ]
