# Generated by Django 6.0.8 on 2026-09-16 17:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('clinics', '0004_clinic_unique_clinic_name_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(help_text='Ex. boîte, comprimé, flacon.', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('min_threshold', models.PositiveIntegerField(default=0)),
                ('max_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('low_stock_alerted', models.BooleanField(default=False)),
                ('overstock_alerted', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField()),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.medication')),
            ],
            options={
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase', 'Achat'), ('dispense', 'Dispensation (facture)'), ('return', 'Retour au stock (modification/annulation de facture)'), ('adjustment', 'Ajustement manuel')], max_length=20)),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stockbatch')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='billing.invoice')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.medication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['clinic'], name='pharmacy_me_clinic__4ada53_idx'),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_medication_name_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.CheckConstraint(condition=models.Q(('max_threshold__isnull', True), ('max_threshold__gte', models.F('min_threshold')), _connector='OR'), name='medication_max_threshold_gte_min_threshold'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['clinic', 'medication'], name='pharmacy_st_clinic__9390ad_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['medication', 'expiry_date'], name='pharmacy_st_medicat_40b0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['clinic', 'medication'], name='pharmacy_st_clinic__22664f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['invoice'], name='pharmacy_st_invoice_d93654_idx'),
        ),
    ]
