# Generated by Django 6.0.8 on 2026-10-08 14:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def pack_price_from_unit_price(apps, schema_editor):
    # Médicaments existants : un seul niveau d'unité (units_per_pack = 1), le conditionnement est
    # donc l'unité elle-même et a le même prix.
    Medication = apps.get_model("pharmacy", "Medication")
    Medication.objects.update(pack_price=models.F("unit_price"))


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_inpatient_billing'),
        ('pharmacy', '0002_non_negative_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='allow_unit_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pack_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='medication',
            name='pack_unit',
            field=models.CharField(blank=True, help_text='Ex. boîte, plaquette.', max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='received_in',
            field=models.CharField(choices=[('pack', 'Conditionnement'), ('unit', 'Unité')], default='unit', max_length=10),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit',
            field=models.CharField(help_text='Unité de base. Ex. comprimé, gélule, flacon.', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.CheckConstraint(condition=models.Q(('units_per_pack__gte', 1)), name='medication_units_per_pack_gte_1'),
        ),
        migrations.RunPython(pack_price_from_unit_price, migrations.RunPython.noop),
    ]
