# Generated by Django 6.0.8 on 2026-10-07 13:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_currency'),
        ('clinics', '0007_inpatient_billing'),
        ('departments', '0002_department_type_status'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('free', 'Libre'), ('occupied', 'Occupé'), ('cleaning', 'En nettoyage'), ('out_of_service', 'Hors service')], default='free', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='clinics.clinic')),
            ],
            options={
                'ordering': ['room__number', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('admitted', 'Admis'), ('discharged', 'Sorti'), ('cancelled', 'Annulé')], default='planned', max_length=20)),
                ('reason', models.TextField()),
                ('planned_for', models.DateField(blank=True, null=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(blank=True, null=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='clinics.clinic')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='departments.department')),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='doctors.doctor')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='hospitalization.bed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='hospitalization.admission')),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hospitalization.bed')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hospitalization.bed')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['transferred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to='hospitalization.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=30)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='clinics.clinic')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='departments.department')),
            ],
            options={
                'ordering': ['department__name', 'number'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hospitalization.room'),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hospitalization.roomtype'),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='hospitalization.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['clinic', 'status'], name='hospitaliza_clinic__7709be_idx'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(fields=('clinic', 'number'), name='unique_admission_number_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'admitted')), fields=('bed',), name='one_admitted_stay_per_bed'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'admitted')), fields=('patient',), name='one_admitted_stay_per_patient'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['clinic', 'status'], name='hospitaliza_clinic__e02a3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='unique_bed_label_per_room'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_room_type_name_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('nightly_rate__gt', 0)), name='room_type_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('clinic', 'number'), name='unique_room_number_per_clinic'),
        ),
    ]
