# Generated by Django 6.0.8 on 2026-09-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_pharmacist_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English')], default='', max_length=2),
        ),
    ]
