# Generated by Django 6.0.8 on 2026-08-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('is_follow_up', models.BooleanField(default=False)),
                ('chief_complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('validated', 'Validated')], default='draft', max_length=20)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['clinic', 'date'], name='consultatio_clinic__4520ae_idx'), models.Index(fields=['doctor', 'date'], name='consultatio_doctor__1b9659_idx'), models.Index(fields=['patient', 'date'], name='consultatio_patient_1a5171_idx')],
            },
        ),
    ]
