# Generated by Django 6.0.8 on 2026-09-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('completed', 'Terminée'), ('validated', 'Validée')], default='draft', max_length=20),
        ),
    ]
