# Generated by Django 6.0.8 on 2026-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('otp', 'OTP'), ('account_activation', 'Account activation'), ('email_verification', 'Email verification'), ('appointment_created', 'Appointment created'), ('appointment_cancelled', 'Appointment cancelled')], max_length=30),
        ),
    ]
