# Generated by Django 6.0.8 on 2026-08-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_notificationlog_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('otp', 'OTP'), ('account_activation', 'Account activation'), ('email_verification', 'Email verification'), ('appointment_created', 'Appointment created'), ('appointment_cancelled', 'Appointment cancelled'), ('subscription_expiring', 'Subscription expiring'), ('license_expired', 'License expired')], max_length=30),
        ),
    ]
