# Generated by Django 6.0.8 on 2026-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_schedule_in_app_purge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('otp', 'OTP'), ('account_activation', 'Account activation'), ('email_verification', 'Email verification'), ('appointment_created', 'Appointment created'), ('appointment_modified', 'Appointment modified'), ('appointment_cancelled', 'Appointment cancelled'), ('appointment_reminder', 'Appointment reminder'), ('subscription_expiring', 'Subscription expiring'), ('license_expired', 'License expired'), ('stock_low', 'Low stock'), ('stock_overstock', 'Overstock'), ('lab_result_available', 'Lab result available')], max_length=30),
        ),
    ]
