# Generated by Django 6.0.8 on 2026-08-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('day_before_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['clinic', 'date'], name='appointment_clinic__f6186d_idx'), models.Index(fields=['doctor', 'date'], name='appointment_doctor__e7d63f_idx'), models.Index(fields=['patient', 'date'], name='appointment_patient_83aa7a_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
    ]
