# Generated by Django 6.0.8 on 2026-08-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_schedule_day_before_reminder'),
        ('clinics', '0002_clinic_billing_cycle_clinic_current_period_end_and_more'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'checked_in_at'], name='appointment_clinic__44a868_idx'),
        ),
    ]
