# Generated by Django 6.0.8 on 2026-08-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_checked_in_at_appointment_ticket_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_sent_at',
        ),
    ]
