# Generated by Django 6.0.8 on 2026-10-07 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0007_inpatient_billing'),
        ('hospitalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_phone', models.CharField(blank=True, max_length=32)),
                ('visitor_type', models.CharField(choices=[('patient_visit', 'Visite à un patient'), ('companion', 'Accompagnant'), ('supplier', 'Fournisseur'), ('contractor', 'Prestataire'), ('other', 'Autre')], max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('visited_free_text', models.CharField(blank=True, max_length=150)),
                ('checked_in_at', models.DateTimeField()),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('auto_closed', models.BooleanField(default=False)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='clinics.clinic')),
                ('visited_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='hospitalization.admission')),
                ('visited_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at', '-id'],
                'indexes': [models.Index(fields=['clinic', 'checked_out_at'], name='visitors_vi_clinic__e292d2_idx'), models.Index(fields=['clinic', 'checked_in_at'], name='visitors_vi_clinic__20d120_idx')],
            },
        ),
    ]
