# Generated by Django 6.0.8 on 2026-08-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['clinic'], name='departments_clinic__c122cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'code'), name='unique_department_code_per_clinic'), models.UniqueConstraint(fields=('clinic', 'name'), name='unique_department_name_per_clinic')],
            },
        ),
    ]
