# Generated by Django 6.0.8 on 2026-08-10 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('professional_number', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='clinics.clinic')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['clinic'], name='doctors_doc_clinic__bcefb0_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'professional_number'), name='unique_professional_number_per_clinic')],
            },
        ),
    ]
